version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: demo
  mongo-express:
#    image: mongo-express:0.54.0
    image: mongo-express
    ports:
      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
#      ME_CONFIG_MONGODB_SERVER: mongo
#      ME_CONFIG_MONGODB_URL: mongodb://root:toor@mongo:27017/
    depends_on:
      - mongo
    restart: unless-stopped
