name: Build and publish images

on:
  push:
    branches:
      - dev-master

env:
  IMAGE_NAME: "useful"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
#      -
#        name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: |
#            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
#          tags: |
#            type=raw,${{ matrix.version }},enable=${{ matrix.latestNode && matrix.latestOS }}
#            type=raw,${{ matrix.version }}-node${{ matrix.node }},enable=${{ matrix.latestOS }}
#            type=raw,${{ matrix.version }}-${{ matrix.os }},enable=${{ matrix.latestNode }}
#            ${{ matrix.version }}-node${{ matrix.node }}-${{ matrix.os }}
#          flavor: |
#            latest=${{ matrix.latest }}
#            prefix=${{ matrix.prefix }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./apps
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
